[package]
name = "example-history-wasi"
version = "0.1.0"
authors = ["Rust and WebAssembly Working Group"]
edition = "2021"
publish = false
rust-version = "1.64"

[dependencies]
gloo = { path = "../..", default-features = false, features = ["history"] }
