/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // Un comment ones for which sidebar is needed
  /*consoleTimerSidebar: [{type: 'autogenerated', dirName: 'console-timer'}],
  dialogSidebar: [{type: 'autogenerated', dirName: 'dialog'}],
  eventSidebar: [{type: 'autogenerated', dirName: 'event'}],
  fileSidebar: [{type: 'autogenerated', dirName: 'file'}],
  storageSidebar: [{type: 'autogenerated', dirName: 'storage'}],
  timerSidebar: [{type: 'autogenerated', dirName: 'timer'}],*/


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
